### ISSUE TITLE
customize css submit

### ISSUE THREAD

**Issue by Virgilio123** [validformbuilder/validformbuilder#146]
### Expected behavior
I would like to customize the submit button with a bootstrap css class

### Which version/branch of ValidForm Builder do you use?
I use the latest version available with php 8.2.1

**Comment by flangfeldt** [comment]
You can already do that with a little trick. All you need to do is add your own HTML with your custom submit button to the `Navigation` object of the form.

```
$form = new ValidForm("");
$navigation = $form->addNavigation();
$navigation->addHtml('<input type="submit" value="Submit me" class="btn btn-large btn-xlarge btn-primary">');
```
