### ISSUE TITLE
Feature: Required fields in dynamic areas

### ISSUE THREAD

**Issue by kaphert** [validformbuilder/validformbuilder#57]
If you define a dynamic area with required fields the fields are not required in the duplicated areas. I can image that this is expected behavior because otherwise you can't leave an area empty and continue with the form. But with this implementation the required fields in dynamic areas are not that useful.  

The best solution would be to implement https://github.com/neverwoods/validformbuilder/issues/25 together with a solution to have required fields in dynamic areas.

Example code
```php
<?php
$form = new ValidForm('form');
$form->setUseCsrfProtection(false);

$area = $form->addArea(
    "Dynamic area",
    false,
    "dyn-area",
    false,
    [
        "dynamic" => true,
        "dynamicLabel" => "+ add",
    ]
);

$area->addField(
    "field-a",
    "Field A",
    ValidForm::VFORM_STRING,
    [
        "required" => true
    ],
    [
        "required" => "This field is required"
    ],
    [
        "dynamic" => true,
    ]
);

$area->addField(
    "field-b",
    "Field B",
    ValidForm::VFORM_STRING,
    [],
    [],
    [
        "dynamic" => true,
    ]
);

if ($form->isSubmitted() && $form->isValid()) {
    echo $form->valuesAsHtml();
} else {
    echo $form->toHtml();
}
```

**Comment by rvanbaalen** [comment]
This can be implemented once #25 is done.
