### ISSUE TITLE
Move project to validformbuilder namespace

### ISSUE THREAD

**Issue by rvanbaalen** [validformbuilder/validformbuilder#92]
We already have the github.com/validformbuilder namespace, all we have to do is migrate the project over there.

I believe this can be done easily in the settings of the project without the loss of reference for existing projects, forks and stars.

**Comment by flangfeldt** [comment]
How do we handle the namespace change in packagist (Composer)?

**Comment by rvanbaalen** [comment]
This is old but could prove useful for this matter:

https://github.com/composer/packagist/issues/47

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by flangfeldt** [comment]
ValidForm Builder has been moved to validformbuilder/validformbuilder.

**Comment by rvanbaalen** [comment]
Awesome! 👏 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.
